/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/lib/config/cmd-list.js TAP > must match snapshot 1`] = `
Object {
  "affordances": Object {
    "add": "install",
    "add-user": "adduser",
    "apihelp": "help",
    "author": "owner",
    "dist-tags": "dist-tag",
    "find": "search",
    "home": "docs",
    "ic": "ci",
    "info": "view",
    "innit": "init",
    "install-clean": "ci",
    "isntall": "install",
    "isntall-clean": "ci",
    "issues": "bugs",
    "la": "ll",
    "login": "adduser",
    "ogr": "org",
    "r": "uninstall",
    "remove": "uninstall",
    "rm": "uninstall",
    "rum": "run-script",
    "show": "view",
    "sit": "cit",
    "udpate": "update",
    "unlink": "uninstall",
    "upgrade": "update",
    "urn": "run-script",
    "verison": "version",
  },
  "aliases": Object {
    "add": "install",
    "add-user": "adduser",
    "apihelp": "help",
    "author": "owner",
    "c": "config",
    "cit": "install-ci-test",
    "clean-install": "ci",
    "clean-install-test": "cit",
    "create": "init",
    "ddp": "dedupe",
    "dist-tags": "dist-tag",
    "find": "search",
    "home": "docs",
    "i": "install",
    "ic": "ci",
    "info": "view",
    "innit": "init",
    "install-clean": "ci",
    "isntall": "install",
    "isntall-clean": "ci",
    "issues": "bugs",
    "it": "install-test",
    "la": "ll",
    "list": "ls",
    "ln": "link",
    "login": "adduser",
    "ogr": "org",
    "r": "uninstall",
    "rb": "rebuild",
    "remove": "uninstall",
    "rm": "uninstall",
    "rum": "run-script",
    "run": "run-script",
    "s": "search",
    "se": "search",
    "show": "view",
    "sit": "cit",
    "t": "test",
    "tst": "test",
    "udpate": "update",
    "un": "uninstall",
    "unlink": "uninstall",
    "unstar": "star",
    "up": "update",
    "upgrade": "update",
    "urn": "run-script",
    "v": "view",
    "verison": "version",
  },
  "cmdList": Array [
    "ci",
    "install-ci-test",
    "install",
    "install-test",
    "uninstall",
    "cache",
    "config",
    "set",
    "get",
    "update",
    "outdated",
    "prune",
    "pack",
    "find-dupes",
    "dedupe",
    "hook",
    "rebuild",
    "link",
    "publish",
    "star",
    "stars",
    "adduser",
    "login",
    "logout",
    "unpublish",
    "owner",
    "access",
    "team",
    "deprecate",
    "shrinkwrap",
    "token",
    "profile",
    "audit",
    "fund",
    "org",
    "help",
    "help-search",
    "ls",
    "ll",
    "search",
    "view",
    "init",
    "version",
    "edit",
    "explore",
    "docs",
    "repo",
    "bugs",
    "root",
    "prefix",
    "bin",
    "whoami",
    "dist-tag",
    "ping",
    "test",
    "stop",
    "start",
    "restart",
    "run-script",
    "completion",
    "doctor",
  ],
  "plumbing": Array [
    "birthday",
  ],
  "shorthands": Object {
    "c": "config",
    "cit": "install-ci-test",
    "clean-install": "ci",
    "clean-install-test": "cit",
    "create": "init",
    "ddp": "dedupe",
    "i": "install",
    "it": "install-test",
    "list": "ls",
    "ln": "link",
    "rb": "rebuild",
    "run": "run-script",
    "s": "search",
    "se": "search",
    "t": "test",
    "tst": "test",
    "un": "uninstall",
    "unstar": "star",
    "up": "update",
    "v": "view",
  },
}
`
