/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/tap/flat-options.js TAP basic > flat options 1`] = `
Object {
  "@scope:registry": "@scope:registry",
  "//nerf.dart:_authToken": "//nerf.dart:_authToken",
  "access": "access",
  "allowSameVersion": "allow-same-version",
  "alwaysAuth": "always-auth",
  "audit": "audit",
  "auditLevel": "audit-level",
  "authType": "auth-type",
  "before": "before",
  "binLinks": "bin-links",
  "browser": "browser",
  "ca": "ca",
  "cache": "cache/_cacache",
  "cacheLockRetries": "cache-lock-retries",
  "cacheLockStale": "cache-lock-stale",
  "cacheLockWait": "cache-lock-wait",
  "cacheMax": "cache-max",
  "cacheMin": "cache-min",
  "cafile": "cafile",
  "cert": "cert",
  "cidr": "cidr",
  "color": true,
  "commitHooks": "commit-hooks",
  "defaultTag": "tag",
  "depth": "depth",
  "description": "description",
  "dmode": 511,
  "dryRun": "dry-run",
  "editor": "editor",
  "engineStrict": "engine-strict",
  "fmode": 438,
  "force": "force",
  "formatPackageLock": "format-package-lock",
  "fund": "fund",
  "git": "git",
  "gitTagVersion": "git-tag-version",
  "global": "global",
  "globalPrefix": "/usr/local",
  "globalStyle": "global-style",
  "hashAlgorithm": "sha1",
  "includeStaged": undefined,
  "key": "key",
  "legacyBundling": "legacy-bundling",
  "localPrefix": "/path/to/npm/cli",
  "lockFile": Object {
    "retries": "cache-lock-retries",
    "stale": "cache-lock-stale",
    "wait": "cache-lock-wait",
  },
  "log": Object {},
  "message": "message",
  "metricsRegistry": "metrics-registry",
  "nodeBin": "/path/to/some/node",
  "nodeVersion": "1.2.3",
  "npmBin": "/path/to/npm/bin.js",
  "npmCommand": "test",
  "npmSession": "12345",
  "npmVersion": "7.6.5",
  "offline": "offline",
  "omit": Array [],
  "otp": "otp",
  "packageLock": "package-lock",
  "packageLockOnly": "package-lock-only",
  "preferOffline": "prefer-offline",
  "preferOnline": "prefer-online",
  "prefix": "/path/to/npm/cli",
  "preid": "preid",
  "projectScope": "@npmcli",
  "readOnly": "read-only",
  "rebuildBundle": "rebuild-bundle",
  "registry": "registry",
  "retry": Object {
    "factor": "fetch-retry-factor",
    "maxTimeout": "fetch-retry-maxtimeout",
    "minTimeout": "fetch-retry-mintimeout",
    "retries": "fetch-retries",
  },
  "save": "save",
  "saveBundle": "save-bundle",
  "saveDev": "save-dev",
  "saveExact": "save-exact",
  "saveOptional": "save-optional",
  "savePeer": "save-peer",
  "savePrefix": "save-prefix",
  "saveProd": "save-prod",
  "scope": "@npmcli",
  "scriptShell": "script-shell",
  "searchexclude": "searchexclude",
  "searchlimit": "searchlimit",
  "searchopts": "searchopts",
  "searchstaleness": "searchstaleness",
  "sendMetrics": "send-metrics",
  "signGitCommit": "sign-git-commit",
  "signGitTag": "sign-git-tag",
  "strictSSL": "strict-ssl",
  "tag": "tag",
  "tagVersionPrefix": "tag-version-prefix",
  "tmp": "/tmp",
  "umask": 18,
  "userAgent": "user-agent",
  "viewer": "viewer",
}
`
