/* IMPORTANT
 * This snapshot file is auto-generated, but designed for humans.
 * It should be checked into source control and tracked carefully.
 * Re-generate by setting TAP_SNAPSHOT=1 and running tests.
 * Make sure to inspect the output below.  Do not ignore changes!
 */
'use strict'
exports[`test/config-locations.js TAP basic > initial data 1`] = `
Object {
  "_auth": null,
  "@hello:registry": "https://corp.npm.com",
  "//hello": "itsme",
  "access": null,
  "all": false,
  "allowSameVersion": false,
  "audit": true,
  "auditLevel": null,
  "authType": "web",
  "before": null,
  "binLinks": true,
  "browser": null,
  "ca": Array [],
  "cache": "/Users/lukekarrys/.npm/_cacache",
  "cafile": undefined,
  "call": null,
  "cert": null,
  "cidr": null,
  "ciName": null,
  "color": false,
  "commitHooks": true,
  "defaultTag": "latest",
  "depth": 1,
  "diff": Array [],
  "diffDstPrefix": "b/",
  "diffIgnoreAllSpace": false,
  "diffNameOnly": false,
  "diffNoPrefix": false,
  "diffSrcPrefix": "a/",
  "diffText": false,
  "diffUnified": 3,
  "dryRun": false,
  "editor": "code -r -w",
  "engineStrict": false,
  "force": false,
  "foregroundScripts": false,
  "formatPackageLock": true,
  "fund": true,
  "git": "git",
  "gitTagVersion": true,
  "global": false,
  "globalconfig": null,
  "globalPrefix": null,
  "heading": "npm",
  "httpsProxy": null,
  "ifPresent": false,
  "ignoreScripts": false,
  "include": Array [],
  "includeStaged": false,
  "includeWorkspaceRoot": false,
  "installLinks": false,
  "installStrategy": "hoisted",
  "json": false,
  "key": null,
  "legacyPeerDeps": false,
  "localAddress": null,
  "localPrefix": "/Users/lukekarrys/projects/npm/cli/workspaces/config",
  "location": "user",
  "lockfileVersion": null,
  "logColor": false,
  "logsDir": "/Users/lukekarrys/.npm/_logs",
  "maxSockets": 15,
  "message": "%s",
  "nodeBin": "/Users/lukekarrys/.fnm/node-versions/v20.2.0/installation/bin/node",
  "noProxy": null,
  "npxCache": "/Users/lukekarrys/.npm/_npx",
  "offline": false,
  "omit": Array [],
  "omitLockfileRegistryResolved": false,
  "package": Array [],
  "packageLock": true,
  "packDestination": ".",
  "parseable": false,
  "preferDedupe": false,
  "preferOffline": false,
  "preferOnline": false,
  "prefix": null,
  "preid": null,
  "progress": false,
  "projectScope": null,
  "provenance": false,
  "provenanceFile": null,
  "proxy": null,
  "readOnly": false,
  "rebuildBundle": true,
  "registry": "https://registry.npmjs.org/",
  "replaceRegistryHost": "npmjs",
  "retry": Object {
    "factor": 10,
    "maxTimeout": 60000,
    "minTimeout": 10000,
    "retries": 2,
  },
  "save": true,
  "saveBundle": false,
  "savePrefix": "^",
  "saveType": undefined,
  "scope": null,
  "scriptShell": null,
  "search": Object {
    "description": true,
    "exclude": null,
    "limit": 20,
    "opts": null,
    "staleness": 900,
  },
  "shell": "/opt/homebrew/bin/zsh",
  "signGitCommit": false,
  "signGitTag": false,
  "silent": false,
  "strictPeerDeps": false,
  "strictSSL": true,
  "tagVersionPrefix": "v",
  "timeout": 300000,
  "tufCache": "/Users/lukekarrys/.npm/_tuf",
  "umask": 0,
  "unicode": true,
  "userAgent": "npm/null node/v20.2.0 darwin arm64 workspaces/false",
  "workspacesEnabled": true,
  "workspacesSet": false,
  "workspacesUpdate": true,
}
`
